CREATE TABLE BOOKS(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  book_name VARCHAR(60) NOT NULL UNIQUE,
  author VARCHAR(60) NOT NULL,
  price DOUBLE NOT NULL,
  book_category VARCHAR(45) NOT NULL,
  status VARCHAR(10) NOT NULL,
  photo VARCHAR(60) NOT NULL,
  email VARCHAR(30) NOT NULL
);